---
apiVersion: v1
kind: Service
metadata:
  name: exostic-com
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    com.docker.project: exostic-com
